[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts"]
# ffi = true = Foundry 测试可以执行本地脚本/外部程序
# ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
